functionID: dfn_68cb00a3a36c8cfb4d3ac889
settings:
  - name: 'functionApiKey'
    label: 'apiKey'
    description: 'function API key'
    required: true
    sensitive: true
    type: 'STRING'
displayName: my function
resourceType: "DESTINATION"
description: my function description